### ISSUE TITLE
Resolve latency issue in history endpoint

### ISSUE THREAD

**Issue by amitschang** [ssec-jhu/evolver-ng#183]
The standard history implementation is file-backed, which has a lot of nice features but even with the time-based partitioning it is noticeably slow on the raspberry pi.

Maybe storing a certain window in-memory, finding a format more suitable, or maybe just tuning partition size, etc might help. 

subtasks:
- [ ] make json reading more efficient by not requiring sampling (see #184)
- [ ] Keep in memory buffer

**Comment by jamienoss** [comment]
Perhaps we just need a newer/better SD card. It shouldn't be slow.
How slow is it, and how much was being written for you to notice this?

**Comment by amitschang** [comment]
It is a brand new SD card. I think one thing to blame is that there is a scan to get schema, but this should not be necessary. First shot could be to remove the need for that, then keep a few hours or so in memory, or similar
